# General Jekyll Config
url: http://tobanwiebe.com
highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
    syntax_highlighter: rouge
lsi: false
exclude: [LICENSE, CNAME, README.md, TODO.md, .gitignore, Gemfile, Gemfile.lock]
permalink: /blog/:year/:month/:title
tag_permalink_style: pretty

#TAGS
tag_page_layout: tag_page
tag_page_dir: tag
